---
name: PlasticSCM
description: Checks out a PlasticSCM repository instead of a git repository.
author: https://github.com/lightforgegames
requirements: []
configuration:
  properties:
    workspacename:
      type:  string
