---
name: PlasticSCM
description: "Checks out a PlasticSCM repository instead of a git repository. Credits to LightForgeGames for the original plugin: https://github.com/lightforgegames"
author: https://github.com/alta-vr
requirements: []
configuration:
  properties:
    workspacename:
      type:  string
